# Generated by Django 2.2.1 on 2019-05-23 10:05

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=100)),
                ('single_line_body', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('date_of_publish', models.DateField()),
                ('image', models.ImageField(upload_to='blog_image')),
                ('seo_title', models.CharField(max_length=50, null=True)),
                ('seo_description', models.TextField(null=True)),
                ('seo_keyword', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
